version: "3"
services:
  main_bot:
    build:
      context: .
    ports:
      - "127.0.0.1:5000:5000"
    restart: always
    volumes:
      - "./src:/scripts"
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    command: >
      /bin/bash -c "
      cd /scripts &&
      python3 app.py"